requires 'Config::IniFiles';
requires 'SQL::Translator', '>= 0.11018';
requires 'DBIx::Class';
requires 'DBI';
requires 'DBD::mysql';
requires 'HTTP::Tiny';
requires 'Text::Glob';
requires 'Text::CSV';
requires 'URI::Escape';
requires 'XML::LibXML';
requires 'XML::Simple';
requires 'Moose';

test_requires 'Test::Warnings';
test_requires 'Test::Differences';
test_requires 'Test::Exception';
test_requires 'Devel::Peek';
test_requires 'Devel::Cycle';
test_requires 'Error';
test_requires 'PadWalker';
test_requires 'IO::String';
test_requires 'Config::General';
test_requires 'Test::Perl::Critic';
test_requires 'Perl::Critic::Utils';
